### ISSUE TITLE
`rename_dimension` does not support `axis="components"`

### ISSUE THREAD

**Issue by Luthaf** [metatensor/metatensor#520]
This makes sense for the other dimension manipulation operations, but renaming a component should be fine.

**Comment by jwa7** [comment]
+1

**Comment by PicoCentauri** [comment]
I think I implemented the renaming in the first place. If this is really important I can deal with it, otherwise I agree that this is a good first issue and I can help with the implementation.

**Comment by ppegolo** [comment]
I'll do it
