### ISSUE TITLE
Warn when creating/exporting a `MetatensorAtomisticModel` without units

### ISSUE THREAD

**Issue by PicoCentauri** [metatensor/metatensor#630]
When creating an MetatensorAtomisticModel instance it is allowed to keep the units as empty strings. This is allowed and  values will be passed to MD engines without conversion. However, this could be problematic when switching engines. In metatensor-models we [warn](https://github.com/lab-cosmo/metatensor-models/blob/2bc152fab8ae7eb38893ab70d56710d266180c95/src/metatensor/models/utils/export.py#L25-L38) users about these possible issues and it might be useful to port these warnings directly into `metatensor`.

See also https://github.com/lab-cosmo/metatensor-models/pull/185#discussion_r1613360706

**Comment by Luthaf** [comment]
Steps to solve this:

- in the `save()` method (https://github.com/metatensor/metatensor/blob/7936af26dcc11dc24fd6379788aec8cf3ded2b4a/python/metatensor-torch/metatensor/torch/atomistic/model.py#L466), add a check that the units are fully defined in `ModelCapabilities`, including all [standard outputs](https://docs.metatensor.org/latest/atomistic/outputs/index.html). Code to do this can take inspiration from metatrain.
- add a test checking that the expected warning is sent to the user when trying to save a model with missing units.

**Comment by SanggyuChong** [comment]
i'll take this?
