### ISSUE TITLE
Default argument for `cell` in `metatensor.torch.atomistic.System`?

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#646]
When creating a system, it's annoying to have to set a cell even though the system is non-periodic

**Comment by Luthaf** [comment]
I'm not sure about this. I like that users are forced to think about what the `cell` should be, this lowers the risk that they forget about it. Like I've been bitten by ASE not requiring a value for `pbc` (even if `cell` is set) multiple times already.

**Comment by Luthaf** [comment]
This is unlikely to happen
