### ISSUE TITLE
Unclear error in `join`

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#694]
```
    if axis == "samples":
        tensor_joined = tensor.keys_to_samples("tensor", sort_samples=sort_samples)
                        ~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    else:
        tensor_joined = tensor.keys_to_properties("tensor", sort_samples=sort_samples)
RuntimeError: internal error (this is likely a bug, please report it): invalid new sample names: InvalidParameter("labels names must be unique, got 'tensor' multiple times")
```

**Comment by Luthaf** [comment]
Can you share the code needed to reproduce this error? This might happen if you split twice, but might also be something else.

**Comment by frostedoyster** [comment]
Sorry, actually it happens if you join, split, and join again, due to the fact that the first join introduces a "tensor' label

**Comment by Luthaf** [comment]
Can you share some small snippet that can be used to reproduce the issue? It will then be used to create a test for whatever fix we implement.
