### ISSUE TITLE
Check if model is metatensor atomistic model?

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#697]
I think it would be good to include a function to check if a torch model is a metatensor atomistic model. What makes it difficult is when the model is torchscripted. For now, I'm using this:
```
def is_exported(model: Any) -> bool:
    """Check if a model has been exported to a MetatensorAtomisticModel.

    :param model: The model to check
    :return: :py:obj:`True` if the ``model`` has been exported, :py:obj:`False`
        otherwise.
    """
    # If the model is saved and loaded again, its type is RecursiveScriptModule
    if isinstance(model, MetatensorAtomisticModel):
        return True
    try:
        model._module
        model._capabilities
        model._metadata
        return True
    except:
        return False
```
(note that `getattr` doesn't seem to work on torchscripted models)
@Luthaf

**Comment by Luthaf** [comment]
So `load_atomistic_model` checks the existence of special files in the exported model to ensure this is a metatensor model. We could extract the check into it's own function.

What's your use case for this?

**Comment by frostedoyster** [comment]
In metatrain, we would need to differentiate between exported metatensor atomistic models and models that follow the ModelInterface. Both torchscripted
