### ISSUE TITLE
Better "not implemented" errors for torchscript classes

### ISSUE THREAD

**Issue by frostedoyster** [metatensor/metatensor#737]
Many times when I do something stupid in metatensor-torch, I get errors of this kind:
```
Traceback (most recent call last):
    energies_predicted = predictions["energy"].block() / torch.tensor([len(sys.positions) for sys in systems], device="cuda")
                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
NotImplementedError: '%s' is not implemented for %s
```
Here, a block is being divided by a tensor

**Comment by Luthaf** [comment]
Hmm, this is not an error that comes from metatensor ... Maybe it's from torch? Or a default Python thing?

**Comment by Luthaf** [comment]
Can you share some code to reproduce the error?

**Comment by Luthaf** [comment]
Closing since this can not be reproduced
