### ISSUE TITLE
No-brainer helper to wrap an array into a TensorBlock

### ISSUE THREAD

**Issue by ceriottm** [metatensor/metatensor#745]
In many cases where we need to wrap a torch-based input for use in a metatensor model one needs to create "dummy" Samples and Components. A lot of work has been done already to make this easier with Labels.arange & C but I think it'd be great to have a TensorBlock(values, [samples_names, components_names, properties_names]) that will create dummy labels and carry on, as it further reduces the boilerplate burden of metatensor. 

I'd also add that it would be great to have this functionality implemented at the rust level, to reduce the silly overhead that comes from wrapping.

**Comment by Luthaf** [comment]
We have this already: https://docs.metatensor.org/latest/operations/reference/creation/block_from_array.html

**Comment by Luthaf** [comment]
And we've had this function for more than a year and a half (April 2023): https://github.com/metatensor/metatensor/pull/241

**Comment by ceriottm** [comment]
RTFM LOL. Would it make sense to implement it at the rust level so we avoid all the overhead of doing this in python?

**Comment by Luthaf** [comment]
Closing in favor of the other issue
