### ISSUE TITLE
Rename `master` branch to `main`

### ISSUE THREAD

**Issue by ceriottm** [metatensor/metatensor#748]
I realized that metatensor still uses the non-pc `master` branch name. Politics aside, we use main pretty much throughout, so I'd suggest we do the renaming also here.

**Comment by frostedoyster** [comment]
I renamed almost all our projects to use main, but I didn't touch rascaline and metatensor because they're complex and I didn't want to break stuff

@Code janitors team
@Luthaf @sirmarcel

**Comment by Luthaf** [comment]
I'm fine with changing this, but yes we would need to be careful with updating the CI configuration & all the scripts.
