### ISSUE TITLE
Add chemiscope to the list of engines that can use metatensor models

### ISSUE THREAD

**Issue by Luthaf** [metatensor/metatensor#758]
Now that https://github.com/lab-cosmo/chemiscope/pull/357 is fully released, we should add a page about chemiscope in the "engines" section of the documentation: https://docs.metatensor.org/latest/atomistic/engines/, with a link back to the chemiscope documentation and a short explanation of what the code does.

**Comment by sandrasaade** [comment]
I'll do it
